ignoredBuiltDependencies:
  - '@napi-ffi/get-symbol-from-current-process-h'
  - unrs-resolver

onlyBuiltDependencies:
  - '@napi-ffi/ref-napi'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*commitlint*'
  - lint-staged

shellEmulator: true
